apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: argocd/applications
    repoURL: 'https://github.com/SergeyHudinskiy/app-of-apps-example.git'
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
